import "./globals.css";
import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const orbitron = Orbitron({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        variables: { colorPrimary: "#624cf5" },
      }}
    >
      <html lang="en">
        <body className={orbitron.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
