import { PricingPlan } from "@/types";

export const countryCodes = [
  { code: "+1", country: "🇺🇸 United States" },
  { code: "+1", country: "🇨🇦 Canada" },
  { code: "+91", country: "🇮🇳 India" },
  { code: "+44", country: "🇬🇧 United Kingdom" },
  { code: "+61", country: "🇦🇺 Australia" },
  { code: "+971", country: "🇦🇪 UAE" },
  { code: "+966", country: "🇸🇦 Saudi Arabia" },
  { code: "+27", country: "🇿🇦 South Africa" },
  { code: "+65", country: "🇸🇬 Singapore" },
  { code: "+234", country: "🇳🇬 Nigeria" },
  { code: "+92", country: "🇵🇰 Pakistan" },
  { code: "+81", country: "🇯🇵 Japan" },
  { code: "+49", country: "🇩🇪 Germany" },
  { code: "+33", country: "🇫🇷 France" },
  { code: "+39", country: "🇮🇹 Italy" },
  { code: "+86", country: "🇨🇳 China" },
  { code: "+7", country: "🇷🇺 Russia" },
  { code: "+55", country: "🇧🇷 Brazil" },
  { code: "+351", country: "🇵🇹 Portugal" },
  { code: "+31", country: "🇳🇱 Netherlands" },
  { code: "+64", country: "🇳🇿 New Zealand" },
  { code: "+20", country: "🇪🇬 Egypt" },
  { code: "+82", country: "🇰🇷 South Korea" },
  { code: "+46", country: "🇸🇪 Sweden" },
  { code: "+41", country: "🇨🇭 Switzerland" },
  { code: "+32", country: "🇧🇪 Belgium" },
  { code: "+34", country: "🇪🇸 Spain" },
  { code: "+90", country: "🇹🇷 Turkey" },
  { code: "+63", country: "🇵🇭 Philippines" },
  { code: "+60", country: "🇲🇾 Malaysia" },
  { code: "+66", country: "🇹🇭 Thailand" },
  { code: "+94", country: "🇱🇰 Sri Lanka" },
  { code: "+357", country: "🇨🇾 Cyprus" },
  { code: "+43", country: "🇦🇹 Austria" },
  { code: "+358", country: "🇫🇮 Finland" },
  { code: "+421", country: "🇸🇰 Slovakia" },
  { code: "+420", country: "🇨🇿 Czech Republic" },
  { code: "+48", country: "🇵🇱 Poland" },
  { code: "+36", country: "🇭🇺 Hungary" },
  { code: "+40", country: "🇷🇴 Romania" },
  { code: "+380", country: "🇺🇦 Ukraine" },
  { code: "+62", country: "🇮🇩 Indonesia" },
  { code: "+84", country: "🇻🇳 Vietnam" },
  { code: "+880", country: "🇧🇩 Bangladesh" },
  { code: "+977", country: "🇳🇵 Nepal" },
  { code: "+965", country: "🇰🇼 Kuwait" },
  { code: "+968", country: "🇴🇲 Oman" },
  { code: "+974", country: "🇶🇦 Qatar" },
  { code: "+961", country: "🇱🇧 Lebanon" },
  { code: "+212", country: "🇲🇦 Morocco" },
  { code: "+216", country: "🇹🇳 Tunisia" },
  { code: "+213", country: "🇩🇿 Algeria" },
  { code: "+54", country: "🇦🇷 Argentina" },
  { code: "+56", country: "🇨🇱 Chile" },
  { code: "+57", country: "🇨🇴 Colombia" },
  { code: "+58", country: "🇻🇪 Venezuela" },
  { code: "+595", country: "🇵🇾 Paraguay" },
  { code: "+598", country: "🇺🇾 Uruguay" },
  { code: "+591", country: "🇧🇴 Bolivia" },
  { code: "+505", country: "🇳🇮 Nicaragua" },
  { code: "+506", country: "🇨🇷 Costa Rica" },
  { code: "+502", country: "🇬🇹 Guatemala" },
  { code: "+503", country: "🇸🇻 El Salvador" },
  { code: "+504", country: "🇭🇳 Honduras" },
  { code: "+592", country: "🇬🇾 Guyana" },
  { code: "+592", country: "🇸🇷 Suriname" },
  { code: "+673", country: "🇧🇳 Brunei" },
  { code: "+675", country: "🇵🇬 Papua New Guinea" },
  { code: "+679", country: "🇫🇯 Fiji" },
  { code: "+682", country: "🇨🇰 Cook Islands" },
  { code: "+685", country: "🇼🇸 Samoa" },
  { code: "+686", country: "🇰🇮 Kiribati" },
  { code: "+691", country: "🇫🇲 Micronesia" },
  { code: "+692", country: "🇲🇭 Marshall Islands" },
  { code: "+850", country: "🇰🇵 North Korea" },
  { code: "+855", country: "🇰🇭 Cambodia" },
  { code: "+856", country: "🇱🇦 Laos" },
  { code: "+993", country: "🇹🇲 Turkmenistan" },
  { code: "+994", country: "🇦🇿 Azerbaijan" },
  { code: "+995", country: "🇬🇪 Georgia" },
  { code: "+996", country: "🇰🇬 Kyrgyzstan" },
  { code: "+998", country: "🇺🇿 Uzbekistan" },
  { code: "+251", country: "🇪🇹 Ethiopia" },
  { code: "+252", country: "🇸🇴 Somalia" },
  { code: "+253", country: "🇩🇯 Djibouti" },
  { code: "+254", country: "🇰🇪 Kenya" },
  { code: "+255", country: "🇹🇿 Tanzania" },
  { code: "+256", country: "🇺🇬 Uganda" },
  { code: "+260", country: "🇿🇲 Zambia" },
  { code: "+261", country: "🇲🇬 Madagascar" },
  { code: "+263", country: "🇿🇼 Zimbabwe" },
  { code: "+264", country: "🇳🇦 Namibia" },
  { code: "+265", country: "🇲🇼 Malawi" },
  { code: "+266", country: "🇱🇸 Lesotho" },
  { code: "+267", country: "🇧🇼 Botswana" },
  { code: "+268", country: "🇸🇿 Eswatini" },
  { code: "+269", country: "🇰🇲 Comoros" },
  { code: "+290", country: "🇸🇭 Saint Helena" },
  { code: "+376", country: "🇦🇩 Andorra" },
  { code: "+377", country: "🇲🇨 Monaco" },
  { code: "+378", country: "🇸🇲 San Marino" },
  { code: "+379", country: "🇻🇦 Vatican City" },
];
export const pricingPlans: PricingPlan[] = [
  {
    id: "Starter-AI-Customer-Support-Agent",
    name: "Starter",
    description: "Perfect for small businesses ",
    monthlyPrice: 99,
    yearlyPrice: 999,
    callLimit: 225,
    leadLimit: 100,
    features: [
      "225  calls / month",
      "Basic  AI responses",
      "Email notifications",
      "24/7 support",
      "Dashboard access",
    ],
  },
  {
    id: "Business-AI-Customer-Support-Agent",
    name: "Professional",
    description: "Ideal for growing businesses",
    monthlyPrice: 199,
    yearlyPrice: 1999,
    callLimit: 500,
    leadLimit: 225,
    popular: true,
    features: [
      "500 calls / month",
      "Custom AI responses",
      "SMS + Email notifications",
      "24/7 premium support",

      "Advanced analytics",
      "Dashboard access",
    ],
  },
  {
    id: "Enterprise-AI-Customer-Support-Agent",
    name: "Enterprise",
    description: "For high-volume businesses",
    monthlyPrice: 299,
    yearlyPrice: 2999,
    callLimit: -1,
    leadLimit: -1,
    features: [
      "Unlimited calls",
      "Custom AI responses",
      "SMS + Email notifications",
      "24/7 premium support",
      "Dashboard access",
    ],
  },
];
